### ISSUE TITLE
Missing SnapMirror methods in v11

### ISSUE THREAD

**Issue by natcrk** [solidfire/postman#10]
Doing a lot of work with SnapMirror from Element to CVO and OnTAP arrays and noticed the SnapMirror methods such as "CreateSnapMirrorRelationship" and "InitializeSnapMirrorRelationship"  are missing

**Comment by ReeseLloyd** [comment]
These methods are intentionally left out.  They are included in the public API for documentation purposes but are intended to only be called by the Element UI.  If you need to automate creation of the relationships, you should leverage the ONTAP API.  The Element API commands only wrap a subset of ONTAP API commands needed for initial configuration.
