### ISSUE TITLE
Mistake in required params for CreateVolume

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/postman#3]
Required param for SolidFire Element OS API Reference Guide v10.0:

![image](https://user-images.githubusercontent.com/16622642/32425222-7deaaf68-c2ec-11e7-8dbd-a73cd25f5313.png)

Postman for Element OS 10:

```
{
    "method": "CreateVolume",
    "params": {
        "name": "<Volume Name>",
        "accountID": <Account ID>,
        "totalSize": <Volume Size in Bytes>,
        "enable512e": <Optional Boolean true or false>,  <======== !!!
        "attributes": {},
        "qos": {
            "minIOPS": <Optional Minimum IOPS>,
            "maxIOPS": <Optional Maximum IOPS>,
            "burstIOPS": <Optional Burst IOPS>,
            "burstTime": 60
        },
        "qosPolicyID": <Optional QoS Policy ID>
    },
    "id": 1
}
```

Reference URL:
https://github.com/solidfire/postman/blob/354c9427c756349f6bd2c4601b49afc9c57d572b/SolidFire-Element10.0-PostmanCollection-20171102.json#L3081

**Comment by scaleoutsean** [comment]
I didn't create PRs for v8, v7, v6 because I'm not sure if it was actually required or not (maybe even in 8.2 it wasn't, now that I think of it).

**Comment by ahaid** [comment]
I merged in your PRs. Thanks for doing the work!
